import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { AuthProvider, ThemeProvider } from '@/contexts';

const montserrat = Montserrat({
    weight: ['400', '500', '600', '700', '800', '900'],
    variable: '--font-montserrat',
    subsets: ['latin'],
    display: 'swap',
});


export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false
}

export const metadata: Metadata = {
    title: 'Tournament Manager',
    description: 'Tournament Manager | Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${montserrat.className} dark`}>
        <AuthProvider>
            <ThemeProvider>
                {children}
            </ThemeProvider>
        </AuthProvider>
        </body>
        </html>
    );
}
