import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';
import { Nunito } from 'next/font/google';
import { AuthProvider, SWRProvider } from '@/contexts';
import './globals.css';

const nunito = Nunito({
    weight: ['400', '600', '800'],
    variable: '--font-nunito',
    subsets: ['latin'],
    display: 'swap',
});

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
};

export const metadata: Metadata = {
    title: 'Tournament Manager',
    description: 'Tournament Manager | Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${nunito.className} dark`}>
        <AuthProvider>
            <SWRProvider>
                {children}
            </SWRProvider>
        </AuthProvider>
        </body>
        </html>
    );
}
