import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { UiProvider } from '@/contexts/UiProvider';
import { Header } from '@/components/Header';

const montserrat = Montserrat({
    weight: ['400', '500', '600', '700', '800', '900'],
    variable: '--font-montserrat',
    subsets: ['latin'],
    display: 'swap',
});


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${montserrat.className} dark`}>
        <UiProvider>
            <Header />
            <main>
                {children}
            </main>
        </UiProvider>
        </body>
        </html>
    );
}
